const PRODUCTS = [
    {
        "id": "p1",
        "name": "Vibrant handcrafted mirror-work ethnic corset blouse",
        "category": "Cor-set Blouse",
        "price": 1499,
        "rating": 5,
        "reviews": 0,
        "description": "Make a striking festive statement with this handcrafted ethnic corset top, intricately detailed with vibrant thread embroidery, traditional mirror work, and charm-accented cowrie shells.",
        "image": "/assets/images/madam/Vibrant handcrafted mirror-work ethnic corset blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p2",
        "name": "Vibrant handcrafted mirror-work ethnic corset blouse Green",
        "category": "Cor-set Blouse",
        "price": 1499,
        "rating": 5,
        "reviews": 0,
        "description": "Make a striking festive statement with this handcrafted ethnic corset top, intricately detailed with vibrant thread embroidery, traditional mirror work, and charm-accented cowrie shells.",
        "image": "/assets/images/madam/IMG_0029.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p3",
        "name": "Vibrant handcrafted mirror-work ethnic corset blouse Dark Green",
        "category": "Cor-set Blouse",
        "price": 1499,
        "rating": 5,
        "reviews": 0,
        "description": "Make a striking festive statement with this handcrafted ethnic corset top, intricately detailed with vibrant thread embroidery, traditional mirror work, and charm-accented cowrie shells.",
        "image": "/assets/images/madam/IMG_0047.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p4",
        "name": "Vibrant handcrafted mirror work ethnic corset blouse",
        "category": "Cor-set Blouse",
        "price": 1499,
        "rating": 5,
        "reviews": 0,
        "description": "Make a striking festive statement with this handcrafted ethnic corset top, intricately detailed with vibrant thread embroidery, traditional mirror work, and charm-accented cowrie shells.",
        "image": "/assets/images/madam/Vibrant handcrafted mirror-work ethnic corset blouse Blue.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p5",
        "name": "Black Beaded Corset Blouse",
        "category": "Designer Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "A glamorous black sweetheart-neck corset blouse, fully studded with tone-on-tone beads and styled with an alluring lace-up back tie.",
        "image": "/assets/images/madam/Black Beaded Corset Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p6",
        "name": "Mustard Yellow Mirror Work Blouse",
        "category": "Designer Blouse",
        "price": 1299,
        "rating": 5,
        "reviews": 0,
        "description": "vibrant mustard-yellow deep V-neck blouse encrusted with dense mirror work, perfect for haldi and festive wear.",
        "image": "/assets/images/madam/Golden Mustard Mirror Work Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p7",
        "name": "vibrant mustard-yellow deep V-neck blouse encrusted with dense mirror work, perfect for haldi and festive wear.",
        "category": "Designer Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "A modern black sleeveless blouse featuring a sharp chevron sequin pattern and a sweetheart neck for sleek evening styling.",
        "image": "/assets/images/madam/Black Sequined Chevron Crop Top.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p8",
        "name": "Quilted Black Embellished Top",
        "category": "Designer Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "An elegant black padded corset top highlighting delicate lattice beadwork and a classic tie-up back detail.",
        "image": "/assets/images/madam/Midnight Quilted Pearl Bustier Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    }
];