const PRODUCTS = [
    {
        "id": "p1",
        "name": "Vibrant handcrafted mirror-work ethnic corset blouse",
        "category": "Cor-set Blouse",
        "price": 1499,
        "rating": 5,
        "reviews": 0,
        "description": "Make a striking festive statement with this handcrafted ethnic corset top, intricately detailed with vibrant thread embroidery, traditional mirror work, and charm-accented cowrie shells.",
        "image": "/assets/images/madam/Vibrant handcrafted mirror-work ethnic corset blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p2",
        "name": "Vibrant handcrafted mirror-work ethnic corset blouse Green",
        "category": "Cor-set Blouse",
        "price": 1499,
        "rating": 5,
        "reviews": 0,
        "description": "Make a striking festive statement with this handcrafted ethnic corset top, intricately detailed with vibrant thread embroidery, traditional mirror work, and charm-accented cowrie shells.",
        "image": "/assets/images/madam/IMG_0029.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p3",
        "name": "Vibrant handcrafted mirror-work ethnic corset blouse Dark Green",
        "category": "Cor-set Blouse",
        "price": 1499,
        "rating": 5,
        "reviews": 0,
        "description": "Make a striking festive statement with this handcrafted ethnic corset top, intricately detailed with vibrant thread embroidery, traditional mirror work, and charm-accented cowrie shells.",
        "image": "/assets/images/madam/IMG_0047.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p4",
        "name": "Vibrant handcrafted mirror work ethnic corset blouse",
        "category": "Cor-set Blouse",
        "price": 1499,
        "rating": 5,
        "reviews": 0,
        "description": "Make a striking festive statement with this handcrafted ethnic corset top, intricately detailed with vibrant thread embroidery, traditional mirror work, and charm-accented cowrie shells.",
        "image": "/assets/images/madam/Vibrant handcrafted mirror-work ethnic corset blouse Blue.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p5",
        "name": "Black Beaded Corset Blouse",
        "category": "Designer Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "A glamorous black sweetheart-neck corset blouse, fully studded with tone-on-tone beads and styled with an alluring lace-up back tie.",
        "image": "/assets/images/madam/Black Beaded Corset Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p6",
        "name": "Mustard Yellow Mirror Work Blouse",
        "category": "Designer Blouse",
        "price": 1299,
        "rating": 5,
        "reviews": 0,
        "description": "vibrant mustard-yellow deep V-neck blouse encrusted with dense mirror work, perfect for haldi and festive wear.",
        "image": "/assets/images/madam/Golden Mustard Mirror Work Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p7",
        "name": "vibrant mustard-yellow deep V-neck blouse encrusted with dense mirror work, perfect for haldi and festive wear.",
        "category": "Designer Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "A modern black sleeveless blouse featuring a sharp chevron sequin pattern and a sweetheart neck for sleek evening styling.",
        "image": "/assets/images/madam/Black Sequined Chevron Crop Top.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p8",
        "name": "Quilted Black Embellished Top",
        "category": "Designer Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "An elegant black padded corset top highlighting delicate lattice beadwork and a classic tie-up back detail.",
        "image": "/assets/images/madam/Midnight Quilted Pearl Bustier Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p9",
        "name": "Pastel Sorbet Beaded Corset",
        "category": "Designer Blouse",
        "price": 2499,
        "rating": 5,
        "reviews": 0,
        "description": "A soft pastel multi-colored corset blouse woven with dense beadwork, sweetheart neckline, and a romantic laced back.",
        "image": "/assets/images/madam/Pastel Sorbet Beaded Corset Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p10",
        "name": "Ivory Pastel Threadwork Halter Blouse",
        "category": "Designer Blouse",
        "price": 1499,
        "rating": 5,
        "reviews": 0,
        "description": "A sophisticated high-neck halter top detailed with pastel floral thread embroidery and dainty bead fringe edging.",
        "image": "/assets/images/madam/Ivory Pastel Threadwork Halter Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p11",
        "name": "Black Geometric Sequin Blouse",
        "category": "Designer Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "A chic black sleeveless crop blouse featuring a striking geometric zig-zag pattern in shimmering silver sequins.",
        "image": "/assets/images/madam/Obsidian Zig-Zag Sequined Bustier Blouse.jpeg",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p12",
        "name": "Champagne Gold Zardozi V-Neck Blouse",
        "category": "Designer Blouse",
        "price": 2499,
        "rating": 5,
        "reviews": 0,
        "description": "A rich champagne-gold deep V-neck blouse intricate with delicate sequins, zardozi work, and elegant hanging pearl drop tassels.",
        "image": "/assets/images/madam/Champagne Gold Zardozi V-Neck Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p13",
        "name": "Shimmer Gold Bustier Top",
        "category": "Designer Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "A statement gold corset top styled with heavily beaded cups, sheer-look structured boning, and strap detail.",
        "image": "/assets/images/madam/Golden Glam Corset Bustier Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p14",
        "name": "High-Neck Beaded Fringe Cape Blouse",
        "category": "Designer Blouse",
        "price": 3499,
        "rating": 5,
        "reviews": 0,
        "description": "A high-neck sheer black top adorned with gold and black embroidered shoulder detailing and floor-sweeping beaded tassels.",
        "image": "/assets/images/madam/High-Neck Beaded Fringe Cape Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p15",
        "name": "Antique Gold Zardosi Corset Blouse",
        "category": "Designer Blouse",
        "price": 2499,
        "rating": 5,
        "reviews": 0,
        "description": "Exude royal elegance in this antique gold corset blouse, intricately embroidered with detailed zardosi beadwork. Finished with a flattering plunging neckline, a center tassel motif, and delicate dangling beaded fringes along the hemline, it's the ultimate statement piece for bridal lehengas and festive sarees.",
        "image": "/assets/images/madam/Antique Gold Zardosi Corset Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p16",
        "name": "Baby Pink Beaded Fringed Corset Blouse",
        "category": "Designer Blouse",
        "price": 2499,
        "rating": 5,
        "reviews": 0,
        "description": "Soft, feminine, and glamorous—this baby pink corset blouse is completely encrusted with tonal micro-beading. Complete with a structured silhouette and a pearl-style fringe along the lower border, it brings a fresh, chic vibe to sangeet celebrations and cocktail wear.",
        "image": "/assets/images/madam/Baby Pink Beaded Fringed Corset Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p17",
        "name": "Glamorous Black Embellished Corset Blouse",
        "category": "Designer Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "Turn heads in this striking black corset featuring structured bust detailing, intricate tonal threadwork, and shimmering sequin embroidery. Styled with slim shoulder straps and a sweetheart neckline, it pairs effortlessly with modern draped sarees and flared fusion skirts.",
        "image": "/assets/images/madam/Glamorous Black embellished corset Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p18",
        "name": "Glamorous Green Embellished Corset Blouse",
        "category": "Designer Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "Crafted in a rich emerald green shade, this corset blouse highlights opulent floral sequin patterns and structured boning for a contoured fit. Perfect for evening receptions, galas, and high-glam festive occasions.",
        "image": "/assets/images/madam/Glamorous Green embellished corset Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p19",
        "name": "Glamorous Red Embellished Corset Blouse",
        "category": "Designer Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "A classic festive shade transformed into a modern masterpiece. This crimson red bustier corset is adorned with intricate sequin motifs, offering a showstopping silhouette that elevated traditional lehengas and sarees instantly.",
        "image": "/assets/images/madam/Glamorous Red embellished corset Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p20",
        "name": "Glamorous Silver Embellished Corset Blouse",
        "category": "Designer Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "Shine under the lights with this silver sequin corset top. Featuring a sweetheart neckline, defined bust structure, and all-over metallic embellishments, this piece brings instant high-fashion flair to cocktail parties and receptions.",
        "image": "/assets/images/madam/Glamorous Silver embellished corset Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p21",
        "name": "Indo-Western Folk Mirror Work Corset Top",
        "category": "Designer Blouse",
        "price": 1499,
        "rating": 5,
        "reviews": 0,
        "description": "A blend of heritage folk art and modern silhouette, this longline corset top features large center mirror work, tribal thread embroidery, and a silver-beaded cowrie shell hemline. Perfect for styling with flared lehengas, tiered skirts, or dhoti pants for an effortless Indo-Western look.",
        "image": "/assets/images/madam/IMG_0032.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p22",
        "name": "Indo-Western Folk Mirror Work Corset Top",
        "category": "Designer Blouse",
        "price": 1499,
        "rating": 5,
        "reviews": 0,
        "description": "A blend of heritage folk art and modern silhouette, this longline corset top features large center mirror work, tribal thread embroidery, and a silver-beaded cowrie shell hemline. Perfect for styling with flared lehengas, tiered skirts, or dhoti pants for an effortless Indo-Western look.",
        "image": "/assets/images/madam/IMG_0042.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p23",
        "name": "Light Olive Embellished Corset Blouse",
        "category": "Cor-set Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "Step into elegance with this beautifully crafted light olive corset-style blouse. Adorned with intricate hand-embroidery featuring tone-on-tone sequins and fine beadwork, it creates a subtle, glamorous shimmer. The structured boning, sweetheart neckline, and unique pointed asymmetric hemline provide a flawless, flattering fit for high-fashion festive wear.",
        "image": "/assets/images/madam/Light Olive Embellished Corset Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p24",
        "name": "Black and Gold Wave-Pattern Bralette",
        "category": "Cor-set Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "Make a striking statement in this bold bralette top. It features eye-catching parallel wave-patterned hand-embroidery in rich gold beads on a deep black base. The structured sweetheart neckline, slender straps, playful beaded fringe, and dramatic criss-cross lace-up back closure create a sensational Indo-Western evening look.",
        "image": "/assets/images/madam/Black and Gold Wave-Pattern Bralette.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p25",
        "name": "Yellow Lace-Back Corset Blouse",
        "category": "Cor-set Blouse",
        "price": 1999,
        "rating": 5,
        "reviews": 0,
        "description": "Brighten any celebration with this vibrant golden yellow corset blouse. It features a structured sweetheart neckline, boning, and intricate tone-on-tone gilded thread and sequin floral embroidery. The defining features are its modern pointed asymmetric hemline and a sensuous, adjustable criss-cross lace-up back, blending traditional artistry with a contemporary silhouette.",
        "image": "/assets/images/madam/Yellow Lace-Back Corset Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p26",
        "name": "Black Sequin Backless Blouse",
        "category": "Designer Blouse",
        "price": 1599,
        "rating": 5,
        "reviews": 0,
        "description": "Perfect your evening look with this classic and glamorous jet black blouse. Dazzling black sequins provide comprehensive sparkle on a structured, sleeveless silhouette with a simple V-neckline. The back is the highlight, featuring a dramatic, deep V-cutout secured by elegant, slender tie-up straps finished with matching tassels, ensuring you look stunning from every angle.",
        "image": "/assets/images/madam/Black Sequin Backless Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p27",
        "name": "Silver Sequin Backless Blouse",
        "category": "Designer Blouse",
        "price": 1599,
        "rating": 5,
        "reviews": 0,
        "description": "Shine flawlessly in this dazzling silver sequin blouse. Covered entirely in shimmering silver mirror-style sequins, it features a classic sleeveless shape and V-neckline. The striking open back design features a deep V-cutout secured by a delicate, adjustable tie-up strap finished with decorative tassels, making it an ideal companion for metallic-toned sarees or lehengas.",
        "image": "/assets/images/madam/Silver Sequin Backless Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    },
    {
        "id": "p28",
        "name": "Gold Diamond Lattice Corset",
        "category": "Designer Blouse",
        "price": 1599,
        "rating": 5,
        "reviews": 0,
        "description": "Achieve a high-fashion, structured look with this stunning gold corset blouse. It is defined by intricate, all-over diamond-patterned lattice hand-embroidery featuring small mirror accents. The bustier silhouette includes a sweetheart neckline, slender straps, and is secured by a dramatic criss-cross lace-up back with adjustable ties and tassels, perfect for creating a contoured Indo-Western statement.",
        "image": "/assets/images/madam/Gold Sequin Backless Blouse.PNG",
        "in_stock": true,
        "featured": false,
        "sale": false,
        "bestseller": false,
        "original_price": null
    }
];